# reference: https://www.w3schools.com/python/gloss_python_string_slice.asp

onehundredfiftyone_characters = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghija"

len(onehundredfiftyone_characters)
# 151

limit_to_onehundredfifty = onehundredfiftyone_characters[0:150]
len(limit_to_onehundredfifty)
# 150